### ISSUE TITLE
deliver expected results?

### ISSUE THREAD

**Issue by dneise** [fact-project/open_crab_sample_analysis#6]
I was wondering if it would be nice for people who are interested in doing this to show them what to expect?

If I understand it correctly, the result is a theta_square plot (i.e. a file `theta2_plot.pdf`) and an event list, one can do further stuff with (i.e. a file `crab_dl3.hdf5`).

Maybe we would like to show the theta2 plot already in the README and something like the first 5 rows from the dl3 files .. just to wet peoples appetite as well as making it easier to explain what is going on here...

**Comment by maxnoe** [comment]
Good Thing. I will also add the link to the Open Data Talk

**Comment by maxnoe** [comment]
done in #8
